version: '3.7'

services:
  server:
    image: networkstatic/iperf3
    command: ["-s"]
    expose:
      - 5201

  client:
    image: networkstatic/iperf3
    command: ["-c", "server"]
    depends_on:
      - server
