services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    volumes:
      - ./results:/app/results
    command:
      - "server"
    depends_on:
      - server

  server:
    build:
      context: server
      dockerfile: Dockerfile
    expose:
      - 5201