%YAML 1.1

---
apiVersion: v1
kind: Namespace
metadata:
  name: network-test

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: network-test
  name: nginx-deployment
  namespace: network-test
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
      nodeSelector:
        kubernetes.io/hostname: aks-multizone-35578676-vmss000001

---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: network-test
  name: network-test
  namespace: network-test
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    k8s-app: network-test