- hosts: kube_master
  become: yes
  collections:
    - cankush625.multicloudkubernetescluster

  roles:
    - role: kube_master
      control_plane_endpoint_ip: 54.177.87.125
      pod_network_cidr: 10.240.0.0/16
      owner: ec2-user
      group: ec2-user
