apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -v
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: iperf3-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml -v
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
        - args:
            - -s
          image: networkstatic/iperf3
          name: iperf3-server
          ports:
            - containerPort: 5201
          resources: {}
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/hostname: aks-multizone-35578676-vmss000001
status: {}


---

apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml -v
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: iperf3-server
spec:
  ports:
    - name: "5201"
      port: 5201
      targetPort: 5201
  selector:
    io.kompose.service: server
status:
  loadBalancer: {}
