apiVersion: batch/v1
kind: Job
metadata:
  name: iperf3-client
spec:
  template:
    spec:
      containers:
      - image: networkstatic/iperf3
        name: iperf3-client
        args:
            - -c
            - iperf3-server
      restartPolicy: Never
      nodeSelector:
        kubernetes.io/hostname: aks-agentpool-45773067-vmss000000
  backoffLimit: 4
