name: Continuous Deployment

on: [push, pull_request]

permissions:
  contents: read

jobs:
  publish:
    name: PyPI - Publish if this is a tagged commit
    if: startsWith(github.event.ref, 'refs/tags') && github.repository_owner == '888aaen'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
      - name: Build + set TAG env var for later use
        run: |
          python -m build
          echo "TAG=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_ENV
      - name: Publish tagged version to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true

  publish_prerelease:
    name: PyPI - Publish prerelease on merge commit on main
    #if: github.ref == 'refs/heads/main' && github.repository_owner == '888aaen'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build
          python -m pip install -r requirements.txt
      - name: Build
        run: python -m build
      - name: Publish prerelease version to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip_existing: true